/**
 * The `facts` object on an assistant step — the one part of the wire the
 * backend's types do not reach.
 *
 * `StepModel.facts` is declared `dict[str, Any]` in
 * `app/api/assistant/schemas.py`, so FastAPI publishes no schema for it and
 * nothing on either side checks that the frontend reads the keys the backend
 * writes. These types are that check, and they were derived from the
 * `as_record()` methods in `app/initiatives/i8/reservation_assistant.py` and
 * `app/initiatives/i13/reservation_assistant.py`, then verified against payloads
 * generated by running those methods.
 *
 * ## Two rules the shapes below follow, both from the backend
 *
 * **Decimals cross as strings.** `_number()` in both modules is
 * `None if value is None else str(value)`. Every quantity, stock figure and
 * months-of-cover value is therefore `string | null`, never a number. Counts
 * (`openRepairLines`, `consumptionCount12m`, `daysSinceLastMovement`) are real
 * integers and are typed as numbers.
 *
 * **Dates cross as ISO strings or null.** `_iso()` is
 * `None if value is None else value.isoformat()`.
 *
 * ## Why null matters more than usual here
 *
 * Several fields are three-state, and collapsing the third state into a zero or
 * a false changes what the screen tells a planner:
 *
 *   - `waitingBeatsBuying: null` means **cannot say**, not "no". It is null on
 *     every overdue repair, which is 695 of the 788 open lines in this extract,
 *     because comparing a due date in the past against a lead time finds the
 *     repair "sooner" and would recommend waiting for a unit that is 515 days
 *     late. Rendering null as "no" throws away the caveat; rendering it as
 *     "yes" is the bug the backend fixed.
 *   - `stockOnHand: "0"` with `stockIsUnknown: true` means the plant has no
 *     stock record, not that the shelf is empty.
 *   - `monthsOfCover: null` with a `monthsOfCoverReason` means the figure could
 *     not be computed, and the reason is the thing to show.
 */

// --- shared -----------------------------------------------------------------

/** Keys both flows emit. Present on every assessment. */
type FactsCommon = {
  /** The discriminator. Narrow on this before reading anything else. */
  flow: "i08" | "i13"
  plant: string
  /** The sentence the assistant leads with. Also the step's `prompt` prefix. */
  headline: string
  /**
   * Qualifications on the headline. Rendered under the question as a footnote,
   * never folded into it — a sentence that hedges every clause is unreadable.
   * The step's `footnote` field is these joined by newline.
   */
  caveats: string[]
  /** The date the assessment was computed against. Not today's date. */
  referenceDate: string
}

// --- Initiative 08 ----------------------------------------------------------

/** One open repair line behind an I08 assessment. */
export type I08OpenRepair = {
  purchasingDocument: string
  item: string
  /** Decimal-as-string. */
  quantity: string
  raisedAt: string | null
  dueDate: string | null
  /** Positive when past the promised date; null when there is no due date. */
  daysOverdue: number | null
  vendor: string | null
  /**
   * Null where the supplier master does not cover the vendor — a known coverage
   * gap (106 vendors against 454 service suppliers). Show the code, do not
   * invent a name.
   */
  vendorName: string | null
  status: string
  /**
   * False on every open line in this extract: no dispatch movement is recorded
   * against any of them, so no line can be confirmed as physically with the
   * vendor.
   */
  dispatched: boolean
}

export type I08Facts = FactsCommon & {
  flow: "i08"
  materialId: string
  description: string | null
  criticality: string | null
  /** The FR-6 verdict: is there already a unit that could serve this need? */
  repairableUnitExists: boolean
  /** Which rule fired, e.g. `ON_REPAIR_ORDER`, `STOCK_ON_HAND`. */
  sources: string[]
  /** Decimal-as-string. Read with `stockIsUnknown` — see the module note. */
  stockOnHand: string | null
  stockIsUnknown: boolean
  openRepairLines: number
  /** Decimal-as-string. */
  quantityUnderRepair: string | null
  soonestDueDate: string | null
  overdueLines: number
  /** False once any line is overdue: the due date is no longer a forecast. */
  repairDueDateIsReliable: boolean
  newUnitLeadTimeDays: number | null
  /** Three-state. `null` is "cannot say" — see the module note. */
  waitingBeatsBuying: boolean | null
  openRepairs: I08OpenRepair[]
}

// --- Initiative 13 ----------------------------------------------------------

export type I13CrossPlantStock = {
  plant: string
  /** Decimal-as-string. Plants holding nothing are filtered out server-side. */
  stockOnHand: string | null
}

export type I13Facts = FactsCommon & {
  flow: "i13"
  /** Note: `material`, not `materialId`. The two flows differ here. */
  material: string
  /** Decimal-as-string, or null when the pop-up fired before a quantity. */
  requestedQuantity: string | null
  stockOnHand: string | null
  openPoQuantity: string | null
  averageMonthlyConsumption: string | null
  monthsOfCover: string | null
  /** Why the figure is missing. Show this instead of the number when set. */
  monthsOfCoverReason: string | null
  projectedMonthsOfCover: string | null
  daysSinceLastMovement: number | null
  daysSinceLastIssue: number | null
  lastMovementDate: string | null
  consumptionCount12m: number
  consumedQty12m: string | null
  /** SOP aging band: FAST 0-365, SLOW 366-730, NON_MOVING over 730 days. */
  agingBand: string
  inventoryTurns: string | null
  /** The 30-day goods-received-not-issued check. */
  grNotIssuedFlag: boolean
  grNotIssuedDaysSinceGr: number | null
  acquiredVsPlanStatus: string
  /** `OAR`, `MIN_MAX`, and the other values of the scope enum. */
  materialScope: string
  crossPlantStock: I13CrossPlantStock[]
}

/**
 * What a step's `facts` can be.
 *
 * The unknown arm is not defensiveness for its own sake. These types are
 * hand-maintained against a `dict[str, Any]`; the day the backend adds a flow or
 * renames a key, the honest behaviour is to render the headline — which every
 * assessment has — rather than an empty card or a crash.
 */
export type AssistantFacts = I08Facts | I13Facts

export function isI08Facts(facts: unknown): facts is I08Facts {
  return isRecord(facts) && facts.flow === "i08"
}

export function isI13Facts(facts: unknown): facts is I13Facts {
  return isRecord(facts) && facts.flow === "i13"
}

/**
 * The headline from any facts object, known flow or not.
 *
 * The fallback for a shape we do not recognise: every `as_record()` emits
 * `headline`, so this is the one thing safe to read before narrowing.
 */
export function factsHeadline(facts: unknown): string | null {
  if (!isRecord(facts)) return null
  return typeof facts.headline === "string" ? facts.headline : null
}

/** Caveats from any facts object. Empty when absent or malformed. */
export function factsCaveats(facts: unknown): string[] {
  if (!isRecord(facts)) return []
  const caveats = facts.caveats
  if (!Array.isArray(caveats)) return []
  return caveats.filter((c): c is string => typeof c === "string")
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}
