import type { Material } from "@/lib/types"

// ---------------------------------------------------------------------------
// Materials
// ---------------------------------------------------------------------------

export const MATERIALS: Material[] = [
  // Mechanical seals — Milling
  {
    id: "500-14892",
    description: "Seal Assy, Mech Type XR-200",
    manufacturer: "Flowserve",
    manufacturerPartNo: "XR-200-65-VV",
    specs: {
      "Shaft size": "65mm",
      "Seal face": "SiC/SiC",
      Elastomer: "Viton",
      "Pressure rating": "12 bar",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 48200,
    lastPoDate: "14 Mar 2026",
    lastVendor: "Flowserve SA",
    stockLevel: 2,
    leadTimeDays: 21,
  },
  {
    id: "500-14905",
    description: "Seal Assy, Mech Type XR-150",
    manufacturer: "Flowserve",
    manufacturerPartNo: "XR-150-50-VV",
    specs: {
      "Shaft size": "50mm",
      "Seal face": "SiC/SiC",
      Elastomer: "Viton",
      "Pressure rating": "10 bar",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 31400,
    lastPoDate: "2 Feb 2026",
    lastVendor: "Flowserve SA",
    stockLevel: 1,
    leadTimeDays: 21,
  },
  {
    id: "500-15020",
    description: "Cartridge Seal, Type 5610",
    manufacturer: "John Crane",
    manufacturerPartNo: "5610-70-CC",
    specs: {
      "Shaft size": "70mm",
      "Seal face": "Carbon/SiC",
      Elastomer: "EPDM",
      "Pressure rating": "16 bar",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 52600,
    lastPoDate: "28 Jan 2026",
    lastVendor: "John Crane Southern Africa",
    stockLevel: 1,
    leadTimeDays: 28,
  },
  {
    id: "500-15134",
    description: "Split Seal, Type DiaSplit",
    manufacturer: "EagleBurgmann",
    manufacturerPartNo: "DS-80-VIT",
    specs: {
      "Shaft size": "80mm",
      "Seal face": "SiC/SiC",
      Elastomer: "Viton",
      "Pressure rating": "14 bar",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 61300,
    lastPoDate: "9 Dec 2025",
    lastVendor: "EagleBurgmann Africa",
    stockLevel: 0,
    leadTimeDays: 35,
  },

  // Slurry pump impellers — Flotation
  {
    id: "500-08823",
    description: "Impeller, Slurry Pump, AH 6/4",
    manufacturer: "Warman",
    manufacturerPartNo: "AH-6-4-IMP-HC",
    specs: {
      Material: "High-chrome iron",
      "Vane config": "5-vane closed",
      Bore: "60mm",
      Duty: "Heavy slurry",
    },
    category: "Flotation",
    lifecycleStatus: "Active",
    lastPoPrice: 74500,
    lastPoDate: "18 Mar 2026",
    lastVendor: "Weir Minerals Africa",
    stockLevel: 1,
    leadTimeDays: 30,
  },
  {
    id: "500-08841",
    description: "Impeller, Slurry Pump, MDM 100",
    manufacturer: "Metso",
    manufacturerPartNo: "MDM100-IMP",
    specs: {
      Material: "High-chrome iron",
      "Vane config": "4-vane open",
      Bore: "55mm",
      Duty: "Medium slurry",
    },
    category: "Flotation",
    lifecycleStatus: "Active",
    lastPoPrice: 58200,
    lastPoDate: "22 Nov 2025",
    lastVendor: "Zest WEG Group",
    stockLevel: 2,
    leadTimeDays: 24,
  },
  {
    id: "500-08876",
    description: "Impeller, Froth Pump, GIW LSA",
    manufacturer: "KSB",
    manufacturerPartNo: "GIW-LSA-IMP",
    specs: {
      Material: "Elastomer-lined",
      "Vane config": "3-vane",
      Bore: "65mm",
      Duty: "Froth / abrasive",
    },
    category: "Flotation",
    lifecycleStatus: "Active",
    lastPoPrice: 66900,
    lastPoDate: "5 Jan 2026",
    lastVendor: "Hytec Group",
    stockLevel: 0,
    leadTimeDays: 32,
  },
  {
    id: "500-08902",
    description: "Impeller, Slurry Pump, AH 4/3",
    manufacturer: "Warman",
    manufacturerPartNo: "AH-4-3-IMP-HC",
    specs: {
      Material: "High-chrome iron",
      "Vane config": "5-vane closed",
      Bore: "45mm",
      Duty: "Heavy slurry",
    },
    category: "Flotation",
    lifecycleStatus: "Active",
    lastPoPrice: 41800,
    lastPoDate: "14 Feb 2026",
    lastVendor: "Weir Minerals Africa",
    stockLevel: 3,
    leadTimeDays: 21,
  },

  // Conveyor belts, rollers, bearings — Conveyance
  {
    id: "500-22140",
    description: "Bearing, Spherical Roller, Conveyor Idler",
    manufacturer: "SKF",
    manufacturerPartNo: "SKF-22312-CC",
    specs: {
      Bore: "60mm",
      "Seal type": "Labyrinth",
      "Load rating": "95kN",
      Duty: "Troughing idler",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 8400,
    lastPoDate: "11 Mar 2026",
    lastVendor: "BMG (Bearing Man Group)",
    stockLevel: 6,
    leadTimeDays: 7,
  },
  {
    id: "500-22188",
    description: "Conveyor Belt, ST1000 Steel Cord",
    manufacturer: "Continental",
    manufacturerPartNo: "CT-ST1000-1200",
    specs: {
      Width: "1200mm",
      Carcass: "Steel cord",
      "Cover grade": "DIN Y",
      Length: "180m",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 186500,
    lastPoDate: "30 Oct 2025",
    lastVendor: "Invicta Holdings",
    stockLevel: 1,
    leadTimeDays: 45,
  },
  {
    id: "500-22219",
    description: "Conveyor Belt, EP400/3 Fabric",
    manufacturer: "Fenner",
    manufacturerPartNo: "FN-EP400-1050",
    specs: {
      Width: "1050mm",
      Carcass: "EP fabric 3-ply",
      "Cover grade": "DIN X",
      Length: "120m",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 94200,
    lastPoDate: "19 Jan 2026",
    lastVendor: "Invicta Holdings",
    stockLevel: 0,
    leadTimeDays: 38,
  },
  {
    id: "500-22254",
    description: "Troughing Roller Set, 35°",
    manufacturer: "Dunlop",
    manufacturerPartNo: "DL-TR35-127",
    specs: {
      Diameter: "127mm",
      "Trough angle": "35°",
      Shaft: "20mm hex",
      Duty: "Medium",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 4200,
    lastPoDate: "24 Feb 2026",
    lastVendor: "Invicta Holdings",
    stockLevel: 12,
    leadTimeDays: 5,
  },
  {
    id: "500-22301",
    description: "Bearing, Spherical Roller, Head Pulley",
    manufacturer: "SKF",
    manufacturerPartNo: "SKF-22320-CC",
    specs: {
      Bore: "100mm",
      "Seal type": "Labyrinth",
      "Load rating": "156kN",
      Duty: "Head pulley",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 14600,
    lastPoDate: "3 Mar 2026",
    lastVendor: "BMG (Bearing Man Group)",
    stockLevel: 3,
    leadTimeDays: 9,
  },

  // Pressure / level transmitters — Instrumentation
  {
    id: "500-31005",
    description: "Pressure Transmitter, Cerabar PMC21",
    manufacturer: "Endress+Hauser",
    manufacturerPartNo: "PMC21-A1F1H",
    specs: {
      Range: "0–16 bar",
      Output: "4-20mA HART",
      "Process conn": "G1/2",
      Accuracy: "0.15%",
    },
    category: "Instrumentation",
    lifecycleStatus: "Active",
    lastPoPrice: 18900,
    lastPoDate: "27 Feb 2026",
    lastVendor: "Becker Mining South Africa",
    stockLevel: 2,
    leadTimeDays: 14,
  },
  {
    id: "500-31048",
    description: "Pressure Transmitter, EJA430E",
    manufacturer: "Yokogawa",
    manufacturerPartNo: "EJA430E-EAS4",
    specs: {
      Range: "0–10 bar",
      Output: "4-20mA HART",
      "Process conn": "1/2 NPT",
      Accuracy: "0.1%",
    },
    category: "Instrumentation",
    lifecycleStatus: "Active",
    lastPoPrice: 21400,
    lastPoDate: "15 Dec 2025",
    lastVendor: "Motion Control Systems",
    stockLevel: 1,
    leadTimeDays: 18,
  },
  {
    id: "500-31090",
    description: "Pressure Transmitter, 2600T",
    manufacturer: "ABB",
    manufacturerPartNo: "266HSH",
    specs: {
      Range: "0–25 bar",
      Output: "4-20mA HART",
      "Process conn": "G1/2",
      Accuracy: "0.1%",
    },
    category: "Instrumentation",
    lifecycleStatus: "EOL",
    lastPoPrice: 19600,
    lastPoDate: "8 Sep 2025",
    lastVendor: "Motion Control Systems",
    stockLevel: 0,
    leadTimeDays: 21,
  },
  {
    id: "500-31122",
    description: "Level Transmitter, Radar FMR10",
    manufacturer: "Endress+Hauser",
    manufacturerPartNo: "FMR10-A",
    specs: {
      Range: "0–8m",
      Output: "4-20mA",
      "Process conn": "Thread G3/4",
      Frequency: "80GHz",
    },
    category: "Instrumentation",
    lifecycleStatus: "Active",
    lastPoPrice: 15200,
    lastPoDate: "20 Jan 2026",
    lastVendor: "Becker Mining South Africa",
    stockLevel: 3,
    leadTimeDays: 12,
  },

  // Mill bearings — Milling
  {
    id: "500-40011",
    description: "Bearing, Spherical Roller, Mill Trunnion",
    manufacturer: "Timken",
    manufacturerPartNo: "24176-EJA",
    specs: {
      Bore: "380mm",
      "Seal type": "Taconite",
      "Load rating": "1250kN",
      Duty: "Mill trunnion",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 142000,
    lastPoDate: "12 Feb 2026",
    lastVendor: "SEW-Eurodrive SA",
    stockLevel: 1,
    leadTimeDays: 40,
  },
  {
    id: "500-40056",
    description: "Bearing, Deep Groove Ball, Motor DE",
    manufacturer: "NSK",
    manufacturerPartNo: "6316-2RS",
    specs: {
      Bore: "80mm",
      "Seal type": "2RS",
      "Load rating": "40kN",
      Duty: "Motor drive-end",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 3900,
    lastPoDate: "4 Mar 2026",
    lastVendor: "Zest WEG Group",
    stockLevel: 8,
    leadTimeDays: 6,
  },
  {
    id: "500-40098",
    description: "Bearing, Cylindrical Roller, Gearbox",
    manufacturer: "FAG",
    manufacturerPartNo: "NU 2216 ECP",
    specs: {
      Bore: "80mm",
      "Seal type": "Open",
      "Load rating": "85kN",
      Duty: "Gearbox input shaft",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 9800,
    lastPoDate: "17 Nov 2025",
    lastVendor: "SEW-Eurodrive SA",
    stockLevel: 2,
    leadTimeDays: 15,
  },

  // Valves — Milling
  {
    id: "500-19560",
    description: "Control Valve, Globe, easy-E",
    manufacturer: "Fisher",
    manufacturerPartNo: "ED-3-EWT",
    specs: {
      Size: "3in",
      Trim: "Equal %",
      Actuator: "667 spring-diaphragm",
      Body: "WCC",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 89400,
    lastPoDate: "10 Jan 2026",
    lastVendor: "Motion Control Systems",
    stockLevel: 0,
    leadTimeDays: 28,
  },
  {
    id: "500-19602",
    description: "Control Valve, Rotary, Neldisc",
    manufacturer: "Neles",
    manufacturerPartNo: "R21-6IN",
    specs: {
      Size: "6in",
      Trim: "Metal seated",
      Actuator: "Pneumatic quarter-turn",
      Body: "WCB",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 112500,
    lastPoDate: "26 Sep 2025",
    lastVendor: "Hytec Group",
    stockLevel: 1,
    leadTimeDays: 33,
  },
  {
    id: "500-19645",
    description: "Slurry Valve, Knife Gate",
    manufacturer: "Weir",
    manufacturerPartNo: "SG-8IN-EPDM",
    specs: {
      Size: "8in",
      Seat: "EPDM",
      Actuator: "Pneumatic",
      Body: "Ductile iron",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 47200,
    lastPoDate: "5 Feb 2026",
    lastVendor: "Weir Minerals Africa",
    stockLevel: 2,
    leadTimeDays: 20,
  },

  // Electrical motors — Conveyance
  {
    id: "500-55210",
    description: "Motor, TEFC, 132kW 4-pole",
    manufacturer: "WEG",
    manufacturerPartNo: "W22-132M-4",
    specs: {
      Power: "132kW",
      Poles: "4",
      Frame: "315M",
      Efficiency: "IE3",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 98700,
    lastPoDate: "21 Oct 2025",
    lastVendor: "Zest WEG Group",
    stockLevel: 1,
    leadTimeDays: 25,
  },
]

export function getMaterialById(id: string): Material | undefined {
  return MATERIALS.find((m) => m.id === id)
}

// ---------------------------------------------------------------------------
// The chat sessions that used to live here are gone (WS7 phase 5).
//
// `CHAT_SESSIONS`, `getSessionById`, `getActiveSessions` and
// `createDraftSession` backed a scripted conversation that played a
// hand-written script in the browser and wrote nothing anywhere. It has been
// replaced by the reservation assistant under /assistant, which is driven by
// the backend and records every turn in an append-only table.
//
// `MATERIALS` and `getMaterialById` above stay: they are the shared material
// catalogue, re-exported through lib/shared-data/material-catalog.ts and read
// by /materials, the Material 360 drawer and Initiative 7's recommendation
// page. They never had anything to do with the chat.
// ---------------------------------------------------------------------------
