import type { ChatSession, Material } from "@/lib/types"
import { NEW_SESSION_ID } from "@/lib/constants"

// ---------------------------------------------------------------------------
// Materials
// ---------------------------------------------------------------------------

export const MATERIALS: Material[] = [
  // Mechanical seals — Milling
  {
    id: "500-14892",
    description: "Seal Assy, Mech Type XR-200",
    manufacturer: "Flowserve",
    manufacturerPartNo: "XR-200-65-VV",
    specs: {
      "Shaft size": "65mm",
      "Seal face": "SiC/SiC",
      Elastomer: "Viton",
      "Pressure rating": "12 bar",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 48200,
    lastPoDate: "14 Mar 2026",
    lastVendor: "Flowserve SA",
    stockLevel: 2,
    leadTimeDays: 21,
  },
  {
    id: "500-14905",
    description: "Seal Assy, Mech Type XR-150",
    manufacturer: "Flowserve",
    manufacturerPartNo: "XR-150-50-VV",
    specs: {
      "Shaft size": "50mm",
      "Seal face": "SiC/SiC",
      Elastomer: "Viton",
      "Pressure rating": "10 bar",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 31400,
    lastPoDate: "2 Feb 2026",
    lastVendor: "Flowserve SA",
    stockLevel: 1,
    leadTimeDays: 21,
  },
  {
    id: "500-15020",
    description: "Cartridge Seal, Type 5610",
    manufacturer: "John Crane",
    manufacturerPartNo: "5610-70-CC",
    specs: {
      "Shaft size": "70mm",
      "Seal face": "Carbon/SiC",
      Elastomer: "EPDM",
      "Pressure rating": "16 bar",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 52600,
    lastPoDate: "28 Jan 2026",
    lastVendor: "John Crane Southern Africa",
    stockLevel: 1,
    leadTimeDays: 28,
  },
  {
    id: "500-15134",
    description: "Split Seal, Type DiaSplit",
    manufacturer: "EagleBurgmann",
    manufacturerPartNo: "DS-80-VIT",
    specs: {
      "Shaft size": "80mm",
      "Seal face": "SiC/SiC",
      Elastomer: "Viton",
      "Pressure rating": "14 bar",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 61300,
    lastPoDate: "9 Dec 2025",
    lastVendor: "EagleBurgmann Africa",
    stockLevel: 0,
    leadTimeDays: 35,
  },

  // Slurry pump impellers — Flotation
  {
    id: "500-08823",
    description: "Impeller, Slurry Pump, AH 6/4",
    manufacturer: "Warman",
    manufacturerPartNo: "AH-6-4-IMP-HC",
    specs: {
      Material: "High-chrome iron",
      "Vane config": "5-vane closed",
      Bore: "60mm",
      Duty: "Heavy slurry",
    },
    category: "Flotation",
    lifecycleStatus: "Active",
    lastPoPrice: 74500,
    lastPoDate: "18 Mar 2026",
    lastVendor: "Weir Minerals Africa",
    stockLevel: 1,
    leadTimeDays: 30,
  },
  {
    id: "500-08841",
    description: "Impeller, Slurry Pump, MDM 100",
    manufacturer: "Metso",
    manufacturerPartNo: "MDM100-IMP",
    specs: {
      Material: "High-chrome iron",
      "Vane config": "4-vane open",
      Bore: "55mm",
      Duty: "Medium slurry",
    },
    category: "Flotation",
    lifecycleStatus: "Active",
    lastPoPrice: 58200,
    lastPoDate: "22 Nov 2025",
    lastVendor: "Zest WEG Group",
    stockLevel: 2,
    leadTimeDays: 24,
  },
  {
    id: "500-08876",
    description: "Impeller, Froth Pump, GIW LSA",
    manufacturer: "KSB",
    manufacturerPartNo: "GIW-LSA-IMP",
    specs: {
      Material: "Elastomer-lined",
      "Vane config": "3-vane",
      Bore: "65mm",
      Duty: "Froth / abrasive",
    },
    category: "Flotation",
    lifecycleStatus: "Active",
    lastPoPrice: 66900,
    lastPoDate: "5 Jan 2026",
    lastVendor: "Hytec Group",
    stockLevel: 0,
    leadTimeDays: 32,
  },
  {
    id: "500-08902",
    description: "Impeller, Slurry Pump, AH 4/3",
    manufacturer: "Warman",
    manufacturerPartNo: "AH-4-3-IMP-HC",
    specs: {
      Material: "High-chrome iron",
      "Vane config": "5-vane closed",
      Bore: "45mm",
      Duty: "Heavy slurry",
    },
    category: "Flotation",
    lifecycleStatus: "Active",
    lastPoPrice: 41800,
    lastPoDate: "14 Feb 2026",
    lastVendor: "Weir Minerals Africa",
    stockLevel: 3,
    leadTimeDays: 21,
  },

  // Conveyor belts, rollers, bearings — Conveyance
  {
    id: "500-22140",
    description: "Bearing, Spherical Roller, Conveyor Idler",
    manufacturer: "SKF",
    manufacturerPartNo: "SKF-22312-CC",
    specs: {
      Bore: "60mm",
      "Seal type": "Labyrinth",
      "Load rating": "95kN",
      Duty: "Troughing idler",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 8400,
    lastPoDate: "11 Mar 2026",
    lastVendor: "BMG (Bearing Man Group)",
    stockLevel: 6,
    leadTimeDays: 7,
  },
  {
    id: "500-22188",
    description: "Conveyor Belt, ST1000 Steel Cord",
    manufacturer: "Continental",
    manufacturerPartNo: "CT-ST1000-1200",
    specs: {
      Width: "1200mm",
      Carcass: "Steel cord",
      "Cover grade": "DIN Y",
      Length: "180m",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 186500,
    lastPoDate: "30 Oct 2025",
    lastVendor: "Invicta Holdings",
    stockLevel: 1,
    leadTimeDays: 45,
  },
  {
    id: "500-22219",
    description: "Conveyor Belt, EP400/3 Fabric",
    manufacturer: "Fenner",
    manufacturerPartNo: "FN-EP400-1050",
    specs: {
      Width: "1050mm",
      Carcass: "EP fabric 3-ply",
      "Cover grade": "DIN X",
      Length: "120m",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 94200,
    lastPoDate: "19 Jan 2026",
    lastVendor: "Invicta Holdings",
    stockLevel: 0,
    leadTimeDays: 38,
  },
  {
    id: "500-22254",
    description: "Troughing Roller Set, 35°",
    manufacturer: "Dunlop",
    manufacturerPartNo: "DL-TR35-127",
    specs: {
      Diameter: "127mm",
      "Trough angle": "35°",
      Shaft: "20mm hex",
      Duty: "Medium",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 4200,
    lastPoDate: "24 Feb 2026",
    lastVendor: "Invicta Holdings",
    stockLevel: 12,
    leadTimeDays: 5,
  },
  {
    id: "500-22301",
    description: "Bearing, Spherical Roller, Head Pulley",
    manufacturer: "SKF",
    manufacturerPartNo: "SKF-22320-CC",
    specs: {
      Bore: "100mm",
      "Seal type": "Labyrinth",
      "Load rating": "156kN",
      Duty: "Head pulley",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 14600,
    lastPoDate: "3 Mar 2026",
    lastVendor: "BMG (Bearing Man Group)",
    stockLevel: 3,
    leadTimeDays: 9,
  },

  // Pressure / level transmitters — Instrumentation
  {
    id: "500-31005",
    description: "Pressure Transmitter, Cerabar PMC21",
    manufacturer: "Endress+Hauser",
    manufacturerPartNo: "PMC21-A1F1H",
    specs: {
      Range: "0–16 bar",
      Output: "4-20mA HART",
      "Process conn": "G1/2",
      Accuracy: "0.15%",
    },
    category: "Instrumentation",
    lifecycleStatus: "Active",
    lastPoPrice: 18900,
    lastPoDate: "27 Feb 2026",
    lastVendor: "Becker Mining South Africa",
    stockLevel: 2,
    leadTimeDays: 14,
  },
  {
    id: "500-31048",
    description: "Pressure Transmitter, EJA430E",
    manufacturer: "Yokogawa",
    manufacturerPartNo: "EJA430E-EAS4",
    specs: {
      Range: "0–10 bar",
      Output: "4-20mA HART",
      "Process conn": "1/2 NPT",
      Accuracy: "0.1%",
    },
    category: "Instrumentation",
    lifecycleStatus: "Active",
    lastPoPrice: 21400,
    lastPoDate: "15 Dec 2025",
    lastVendor: "Motion Control Systems",
    stockLevel: 1,
    leadTimeDays: 18,
  },
  {
    id: "500-31090",
    description: "Pressure Transmitter, 2600T",
    manufacturer: "ABB",
    manufacturerPartNo: "266HSH",
    specs: {
      Range: "0–25 bar",
      Output: "4-20mA HART",
      "Process conn": "G1/2",
      Accuracy: "0.1%",
    },
    category: "Instrumentation",
    lifecycleStatus: "EOL",
    lastPoPrice: 19600,
    lastPoDate: "8 Sep 2025",
    lastVendor: "Motion Control Systems",
    stockLevel: 0,
    leadTimeDays: 21,
  },
  {
    id: "500-31122",
    description: "Level Transmitter, Radar FMR10",
    manufacturer: "Endress+Hauser",
    manufacturerPartNo: "FMR10-A",
    specs: {
      Range: "0–8m",
      Output: "4-20mA",
      "Process conn": "Thread G3/4",
      Frequency: "80GHz",
    },
    category: "Instrumentation",
    lifecycleStatus: "Active",
    lastPoPrice: 15200,
    lastPoDate: "20 Jan 2026",
    lastVendor: "Becker Mining South Africa",
    stockLevel: 3,
    leadTimeDays: 12,
  },

  // Mill bearings — Milling
  {
    id: "500-40011",
    description: "Bearing, Spherical Roller, Mill Trunnion",
    manufacturer: "Timken",
    manufacturerPartNo: "24176-EJA",
    specs: {
      Bore: "380mm",
      "Seal type": "Taconite",
      "Load rating": "1250kN",
      Duty: "Mill trunnion",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 142000,
    lastPoDate: "12 Feb 2026",
    lastVendor: "SEW-Eurodrive SA",
    stockLevel: 1,
    leadTimeDays: 40,
  },
  {
    id: "500-40056",
    description: "Bearing, Deep Groove Ball, Motor DE",
    manufacturer: "NSK",
    manufacturerPartNo: "6316-2RS",
    specs: {
      Bore: "80mm",
      "Seal type": "2RS",
      "Load rating": "40kN",
      Duty: "Motor drive-end",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 3900,
    lastPoDate: "4 Mar 2026",
    lastVendor: "Zest WEG Group",
    stockLevel: 8,
    leadTimeDays: 6,
  },
  {
    id: "500-40098",
    description: "Bearing, Cylindrical Roller, Gearbox",
    manufacturer: "FAG",
    manufacturerPartNo: "NU 2216 ECP",
    specs: {
      Bore: "80mm",
      "Seal type": "Open",
      "Load rating": "85kN",
      Duty: "Gearbox input shaft",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 9800,
    lastPoDate: "17 Nov 2025",
    lastVendor: "SEW-Eurodrive SA",
    stockLevel: 2,
    leadTimeDays: 15,
  },

  // Valves — Milling
  {
    id: "500-19560",
    description: "Control Valve, Globe, easy-E",
    manufacturer: "Fisher",
    manufacturerPartNo: "ED-3-EWT",
    specs: {
      Size: "3in",
      Trim: "Equal %",
      Actuator: "667 spring-diaphragm",
      Body: "WCC",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 89400,
    lastPoDate: "10 Jan 2026",
    lastVendor: "Motion Control Systems",
    stockLevel: 0,
    leadTimeDays: 28,
  },
  {
    id: "500-19602",
    description: "Control Valve, Rotary, Neldisc",
    manufacturer: "Neles",
    manufacturerPartNo: "R21-6IN",
    specs: {
      Size: "6in",
      Trim: "Metal seated",
      Actuator: "Pneumatic quarter-turn",
      Body: "WCB",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 112500,
    lastPoDate: "26 Sep 2025",
    lastVendor: "Hytec Group",
    stockLevel: 1,
    leadTimeDays: 33,
  },
  {
    id: "500-19645",
    description: "Slurry Valve, Knife Gate",
    manufacturer: "Weir",
    manufacturerPartNo: "SG-8IN-EPDM",
    specs: {
      Size: "8in",
      Seat: "EPDM",
      Actuator: "Pneumatic",
      Body: "Ductile iron",
    },
    category: "Milling",
    lifecycleStatus: "Active",
    lastPoPrice: 47200,
    lastPoDate: "5 Feb 2026",
    lastVendor: "Weir Minerals Africa",
    stockLevel: 2,
    leadTimeDays: 20,
  },

  // Electrical motors — Conveyance
  {
    id: "500-55210",
    description: "Motor, TEFC, 132kW 4-pole",
    manufacturer: "WEG",
    manufacturerPartNo: "W22-132M-4",
    specs: {
      Power: "132kW",
      Poles: "4",
      Frame: "315M",
      Efficiency: "IE3",
    },
    category: "Conveyance",
    lifecycleStatus: "Active",
    lastPoPrice: 98700,
    lastPoDate: "21 Oct 2025",
    lastVendor: "Zest WEG Group",
    stockLevel: 1,
    leadTimeDays: 25,
  },
]

export function getMaterialById(id: string): Material | undefined {
  return MATERIALS.find((m) => m.id === id)
}

// ---------------------------------------------------------------------------
// Chat sessions
// ---------------------------------------------------------------------------



export const CHAT_SESSIONS: ChatSession[] = [
  // 1. Pump seal — Milling — the hero demo. OAR-classified; walks the full
  // conversational consumption-plan capture (§5) through to a confirmable
  // summary (click "Confirm Plan" to see the Tracking ID + SAP reservation
  // generated live, §6-7).
  {
    id: "SPR-2847",
    title: "Pump seal — Milling unit 3",
    navLabel: "Pump seal — Milling",
    navSubtitle: "OAR — plan ready to confirm",
    category: "Milling",
    status: "in_progress",
    materialId: "500-14892",
    requester: "M. Naidoo",
    date: "22 Jul 2026",
    messages: [
      {
        id: "seal-1",
        role: "user",
        authorLabel: "You",
        timestamp: "10:23 AM",
        text: "Show me material 500-14892 — mechanical seal for the milling pump, it's on back order",
      },
      {
        id: "seal-2",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "10:23 AM",
        classification: "500-14892",
        footerNote: "Classified via the Material Router",
      },
      {
        id: "seal-3",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "10:24 AM",
        text: "This material is classified as OAR. A consumption plan is required before proceeding.\n\nBefore proceeding, please provide the intended purpose.",
      },
      {
        id: "seal-4",
        role: "user",
        authorLabel: "You",
        timestamp: "10:24 AM",
        text: "Secondary pump overhaul on Milling unit 3.",
      },
      {
        id: "seal-5",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "10:24 AM",
        text: "Which equipment, project or job is this for?",
      },
      {
        id: "seal-6",
        role: "user",
        authorLabel: "You",
        timestamp: "10:25 AM",
        text: "PUMP-2204.",
      },
      {
        id: "seal-7",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "10:25 AM",
        text: "How many units do you need, and when do you expect to consume them?",
      },
      {
        id: "seal-8",
        role: "user",
        authorLabel: "You",
        timestamp: "10:26 AM",
        text: "3 units, needed by 20 September 2026.",
      },
      {
        id: "seal-9",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "10:26 AM",
        text: "**Consumption Plan**\n\nMaterial: 500-14892\nQuantity: 3\nPurpose: Secondary pump overhaul on Milling unit 3.\nEquipment / Project / Job: PUMP-2204\nPlanned Consumption Date: 20 Sep 2026\n\nReady to confirm?",
        actions: {
          id: "seal-plan-actions",
          accentId: "confirm-plan",
          actions: [
            {
              id: "confirm-plan",
              icon: "check-circle",
              label: "Confirm Plan",
              description: "Creates the Tracking ID and SAP reservation",
            },
            {
              id: "edit-plan",
              icon: "rotate-ccw",
              label: "Edit Plan",
              description: "Go back and change an answer",
            },
          ],
        },
      },
    ],
    workflow: [
      {
        id: "material-identified",
        label: "Material identified",
        status: "done",
        meta: "Auto · 10:23",
      },
      {
        id: "classified-routed",
        label: "Classified & routed",
        status: "done",
        meta: "Routed to OAR Utilization",
      },
      {
        id: "consumption-plan",
        label: "Consumption plan",
        status: "active",
        meta: "Summary ready — awaiting confirmation",
      },
      {
        id: "reservation",
        label: "SAP reservation",
        status: "pending",
        meta: "Created on plan confirmation",
      },
    ],
    emails: [
      {
        id: "seal-email-1",
        status: "sent",
        text: "Requester notified — consumption plan required before this OAR request can proceed",
        time: "10:23 AM",
      },
    ],
    trace: {
      tags: [
        { label: "Milling", kind: "cat" },
        { label: "OAR", kind: "tier" },
        { label: "In progress", kind: "status" },
      ],
      material: "500-14892",
      equipment: "PUMP-2204",
      requester: "M. Naidoo",
      specMatch: "OAR — Order as Required",
      selectionsDone: 2,
      selectionsTotal: 4,
    },
  },

  // 2. Conveyor gearmotor — Conveyance — repairable (80-series), an active
  // repair chain already exists (RC-8005). Demonstrates the Initiative 8
  // advisory duplicate-spend guard (§24) live, in-chat.
  {
    id: "SPR-2851",
    title: "Conveyor gearmotor — CV-14 stacker",
    navLabel: "Conveyor gearmotor",
    navSubtitle: "Repair chain found",
    navBadge: { type: "count", value: 1 },
    category: "Conveyance",
    status: "in_progress",
    materialId: "800-45210",
    requester: "T. Mokoena",
    date: "21 Jul 2026",
    messages: [
      {
        id: "brg-1",
        role: "user",
        authorLabel: "You",
        timestamp: "8:12 AM",
        text: "Need a replacement for material 800-45210 — conveyor gearmotor on the CV-14 stacker, current one's underperforming",
      },
      {
        id: "brg-2",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "8:12 AM",
        classification: "800-45210",
        footerNote: "Classified via the Material Router",
      },
      {
        id: "brg-3",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "8:13 AM",
        text: "A repair for this material is already in progress — PR-81005 raised with Weir Minerals Service Center, 1 unit under repair, expected return 28 Sep 2026. Would you still like to proceed with a new procurement request?",
        actions: {
          id: "brg-actions",
          actions: [
            {
              id: "review-existing",
              icon: "eye",
              label: "Review Existing Repair",
              description: "Open the Repair Register entry for this chain",
            },
            {
              id: "proceed-anyway",
              icon: "send",
              label: "Proceed Anyway",
              description: "Continue with a new procurement request",
            },
            {
              id: "cancel-request",
              icon: "cancel",
              label: "Cancel Request",
              description: "Don't raise a new request",
            },
          ],
        },
      },
    ],
    workflow: [
      {
        id: "material-identified",
        label: "Material identified",
        status: "done",
        meta: "Auto · 08:12",
      },
      {
        id: "classified-routed",
        label: "Classified & routed",
        status: "done",
        meta: "Routed to Repairable Spares",
      },
      {
        id: "duplicate-guard",
        label: "Duplicate-spend guard",
        status: "active",
        meta: "Awaiting decision",
      },
      {
        id: "condition-declaration",
        label: "Condition-to-repair declaration",
        status: "pending",
        meta: "Required before PO release",
      },
    ],
    emails: [
      {
        id: "brg-email-1",
        status: "sent",
        text: "Planner notified — active repair chain found for this material",
        time: "8:13 AM",
      },
    ],
    trace: {
      tags: [
        { label: "Conveyance", kind: "cat" },
        { label: "Repairable", kind: "tier" },
        { label: "In progress", kind: "status" },
      ],
      material: "800-45210",
      equipment: "CV-14 stacker conveyor",
      requester: "T. Mokoena",
      specMatch: "Non-OAR · Repairable spare — 80-series",
      selectionsDone: 2,
      selectionsTotal: 4,
    },
  },

  // 3. Pressure transmitter — Instrumentation — OAR with repeated
  // utilisation this year; demonstrates the OAR-to-Stock reclassification
  // signal (§21) alongside a single-reminder escalation.
  {
    id: "SPR-2839",
    title: "Pressure transmitter — Flotation bank 2",
    navLabel: "Pressure transmitter",
    navSubtitle: "Escalated — plan overdue",
    navBadge: { type: "alert" },
    category: "Instrumentation",
    status: "escalated",
    materialId: "500-31005",
    requester: "S. van Wyk",
    date: "18 Jul 2026",
    messages: [
      {
        id: "pt-1",
        role: "user",
        authorLabel: "You",
        timestamp: "7:40 AM",
        text: "The pressure transmitter 500-31005 on the reagent dosing skid needs replacing again — third time this year",
      },
      {
        id: "pt-2",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "7:41 AM",
        classification: "500-31005",
        footerNote: "Classified via the Material Router",
      },
      {
        id: "pt-3",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "7:42 AM",
        text: "This OAR material has repeated utilisation this year — see the Reclassification review to check whether it should move to Inventory Planning instead.",
      },
      {
        id: "pt-4",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "7:43 AM",
        text: "This material is classified as OAR. A consumption plan is required before proceeding.\n\nBefore proceeding, please provide the intended purpose.",
      },
      {
        id: "pt-5",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "Next day · 8:10 AM",
        text: "It's been over 24 hours since this consumption plan was requested with no response. A reminder has been sent to **S. van Wyk**; this will escalate to the HOD queue if there's still no response.",
      },
    ],
    workflow: [
      {
        id: "material-identified",
        label: "Material identified",
        status: "done",
        meta: "Auto · 07:41",
      },
      {
        id: "classified-routed",
        label: "Classified & routed",
        status: "done",
        meta: "Routed to OAR Utilization",
      },
      {
        id: "consumption-plan",
        label: "Consumption plan",
        status: "active",
        meta: "Overdue — reminder sent",
        tone: "danger",
      },
      {
        id: "reservation",
        label: "SAP reservation",
        status: "pending",
      },
    ],
    emails: [
      {
        id: "pt-email-1",
        status: "sent",
        text: "Session started — consumption plan requested from S. van Wyk",
        time: "7:41 AM",
      },
      {
        id: "pt-email-2",
        status: "pending",
        text: "Escalation to HOD queue queued if no response within 24h",
        time: "Configured",
      },
    ],
    trace: {
      tags: [
        { label: "Instrumentation", kind: "cat" },
        { label: "OAR", kind: "tier" },
        { label: "Escalated", kind: "status" },
      ],
      material: "500-31005",
      equipment: "Reagent dosing skid — bank 2",
      requester: "S. van Wyk",
      specMatch: "OAR — Order as Required",
      selectionsDone: 3,
      selectionsTotal: 4,
    },
  },

  // 4. Impeller — Flotation/Pumping — non-OAR, non-repairable, critical:
  // routes to Initiative 7. Recommendation was returned for revision.
  {
    id: "SPR-2802",
    title: "Impeller — Flotation feed pump FP-2",
    navLabel: "Impeller — Flotation",
    navSubtitle: "Returned for revision",
    category: "Flotation",
    status: "pending_approval",
    materialId: "500-08841",
    requester: "K. Dlamini",
    date: "15 Jul 2026",
    messages: [
      {
        id: "imp-1",
        role: "user",
        authorLabel: "You",
        timestamp: "9:02 AM",
        text: "Impeller on FP-2 is showing heavy wear — material 500-08841, need to know if we should be holding more stock",
      },
      {
        id: "imp-2",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "9:03 AM",
        classification: "500-08841",
        footerNote: "Classified via the Material Router",
      },
      {
        id: "imp-3",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "9:05 AM",
        text: "I've reviewed the planning parameters for this material — demand variability has increased and it's rated high risk. The recommendation was returned by the Commercial Manager for revision; the Engineering Manager has been asked to re-submit with updated lead-time assumptions.",
      },
    ],
    workflow: [
      {
        id: "material-identified",
        label: "Material identified",
        status: "done",
        meta: "Auto · 09:03",
      },
      {
        id: "classified-routed",
        label: "Classified & routed",
        status: "done",
        meta: "Routed to Inventory Planning",
      },
      {
        id: "planning-review",
        label: "Planning parameter review",
        status: "done",
        meta: "Recommendation drafted",
      },
      {
        id: "approval-workflow",
        label: "Approval workflow",
        status: "active",
        meta: "Returned for revision — Engineering Manager",
        tone: "warning",
      },
    ],
    emails: [
      {
        id: "imp-email-1",
        status: "sent",
        text: "Recommendation returned to Engineering Manager for revision",
        time: "9:05 AM",
      },
    ],
    trace: {
      tags: [
        { label: "Flotation", kind: "cat" },
        { label: "Critical", kind: "tier" },
        { label: "Pending approval", kind: "status" },
      ],
      material: "500-08841",
      equipment: "FP-2 flotation feed pump",
      requester: "K. Dlamini",
      specMatch: "Critical — Pumping Circuit",
      selectionsDone: 3,
      selectionsTotal: 4,
    },
  },

  // 5. Control valve — Milling — OAR, consumption plan never submitted;
  // demonstrates the full requester no-response escalation ladder (§19).
  {
    id: "SPR-2860",
    title: "Control valve — Reagent dosing line",
    navLabel: "Control valve",
    navSubtitle: "Escalated — no response",
    navBadge: { type: "alert" },
    category: "Milling",
    status: "escalated",
    materialId: "500-19560",
    requester: "R. Abrahams",
    date: "21 Jul 2026",
    messages: [
      {
        id: "valve-1",
        role: "user",
        authorLabel: "You",
        timestamp: "2:02 PM",
        text: "The reagent dosing control valve keeps sticking — material 500-19560, need a replacement",
      },
      {
        id: "valve-2",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "2:03 PM",
        classification: "500-19560",
        footerNote: "Classified via the Material Router",
      },
      {
        id: "valve-3",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "2:04 PM",
        text: "This material is classified as OAR. A consumption plan is required before proceeding.\n\nBefore proceeding, please provide the intended purpose.",
      },
      {
        id: "valve-4",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "Next day · 2:10 PM",
        text: "We haven't received a response for this consumption plan in 24 hours. A reminder has been sent to **R. Abrahams**.",
      },
      {
        id: "valve-5",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "2 days later · 9:00 AM",
        text: "Still no response after a second reminder. This has now **escalated to the HOD queue** for review.",
      },
    ],
    workflow: [
      {
        id: "material-identified",
        label: "Material identified",
        status: "done",
        meta: "Auto · 14:03",
      },
      {
        id: "classified-routed",
        label: "Classified & routed",
        status: "done",
        meta: "Routed to OAR Utilization",
      },
      {
        id: "consumption-plan",
        label: "Consumption plan",
        status: "active",
        meta: "Overdue — escalated to HOD queue",
        tone: "danger",
      },
      {
        id: "reservation",
        label: "SAP reservation",
        status: "pending",
      },
    ],
    emails: [
      {
        id: "valve-email-1",
        status: "sent",
        text: "Reminder sent to R. Abrahams — consumption plan required",
        time: "2:03 PM",
      },
      {
        id: "valve-email-2",
        status: "sent",
        text: "Second reminder sent — no response",
        time: "Next day · 2:10 PM",
      },
      {
        id: "valve-email-3",
        status: "escalated",
        text: "Escalated to HOD queue — no response from requester in 48h",
        time: "2 days later · 9:00 AM",
      },
    ],
    trace: {
      tags: [
        { label: "Milling", kind: "cat" },
        { label: "OAR", kind: "tier" },
        { label: "Escalated", kind: "status" },
      ],
      material: "500-19560",
      equipment: "Reagent dosing line",
      requester: "R. Abrahams",
      specMatch: "OAR — Order as Required",
      selectionsDone: 3,
      selectionsTotal: 4,
    },
  },

  // 6. Blank draft — opened by sidebar "New session". Type a material query
  // (e.g. "Show me material 500-15134") and the Material Assistant
  // classifies and routes it live, then continues the conversation itself.
  {
    id: NEW_SESSION_ID,
    title: "New session",
    navLabel: "New session",
    navSubtitle: "Draft",
    category: "Milling",
    status: "new",
    materialId: "—",
    requester: "You",
    date: "22 Jul 2026",
    messages: [],
    workflow: [
      {
        id: "material-identified",
        label: "Material identified",
        status: "active",
        meta: "Awaiting input",
      },
      { id: "classified-routed", label: "Classified & routed", status: "pending" },
      { id: "next-step", label: "Routed to the right workflow", status: "pending" },
    ],
    emails: [],
    trace: {
      tags: [{ label: "Draft", kind: "status" }],
      material: "—",
      equipment: "—",
      requester: "You",
      specMatch: "—",
      selectionsDone: 0,
      selectionsTotal: 3,
    },
  },
]

export function getSessionById(id: string): ChatSession | undefined {
  return CHAT_SESSIONS.find((s) => s.id === id)
}

/** Sessions surfaced in the sidebar — completed sessions roll off the active list. */
export function getActiveSessions(): ChatSession[] {
  return CHAT_SESSIONS.filter((s) => s.status !== "completed")
}

/**
 * Synthesizes a fresh "material identification" session for any catalog
 * material — used by /materials row clicks. Only seeds the opening
 * exchange (query + classification card); `ChatWorkspace` takes it from
 * there live — asking for the OAR consumption plan (§5) or surfacing the
 * Initiative 8 duplicate-repair check (§24) itself, via
 * `lib/material-router.ts`.
 */
export function createDraftSession(material: Material): ChatSession {
  return {
    id: `NEW-${material.id}`,
    title: `${material.description} — ${material.category}`,
    navLabel: material.description,
    navSubtitle: "New session",
    category: material.category,
    status: "new",
    materialId: material.id,
    requester: "You",
    date: "22 Jul 2026",
    messages: [
      {
        id: "draft-1",
        role: "user",
        authorLabel: "You",
        timestamp: "Just now",
        text: `Show me material ${material.id} — ${material.description}`,
      },
      {
        id: "draft-2",
        role: "ai",
        authorLabel: "Spares Assistant",
        timestamp: "Just now",
        classification: material.id,
        footerNote: "Classified via the Material Router",
      },
    ],
    workflow: [
      {
        id: "material-identified",
        label: "Material identified",
        status: "done",
        meta: "Auto · just now",
      },
      {
        id: "classified-routed",
        label: "Classified & routed",
        status: "active",
        meta: "See conversation below",
      },
      { id: "next-step", label: "Routed to the right workflow", status: "pending" },
    ],
    emails: [],
    trace: {
      tags: [{ label: material.category, kind: "cat" }, { label: "New", kind: "status" }],
      material: material.id,
      equipment: "—",
      requester: "You",
      specMatch: "Pending classification",
      selectionsDone: 1,
      selectionsTotal: 3,
    },
  }
}
