// GENERATED FILE — do not edit by hand.
// Regenerate with: npm run contract:generate
// Source: data-generator/discovery/{entity_sets,properties}.csv
//
// 21 entity sets, 229 properties, as measured by the
// committed discovery sweep. Checked in on purpose: this is the baseline every
// drift check compares against, and its git diff is the drift report.

import type { SapContract } from "./types"

export const SAP_CONTRACT: SapContract = {
  "PurchaseRequisitionSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "PurchaseRequisitionSet",
    entityType: "PurchaseRequisition",
    keys: ["Banfn","Bnfpo"],
    properties: [
      { name: "Banfn", type: "Edm.String", nullable: false, isKey: true },
      { name: "Bnfpo", type: "Edm.String", nullable: false, isKey: true },
      { name: "Bsart", type: "Edm.String", nullable: false, isKey: false },
      { name: "Loekz", type: "Edm.String", nullable: false, isKey: false },
      { name: "Statu", type: "Edm.String", nullable: false, isKey: false },
      { name: "Frgkz", type: "Edm.String", nullable: false, isKey: false },
      { name: "Frgzu", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ekgrp", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ernam", type: "Edm.String", nullable: false, isKey: false },
      { name: "Afnam", type: "Edm.String", nullable: false, isKey: false },
      { name: "Txz01", type: "Edm.String", nullable: false, isKey: false },
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: false },
      { name: "Lgort", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bednr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Matkl", type: "Edm.String", nullable: false, isKey: false },
      { name: "Reswk", type: "Edm.String", nullable: false, isKey: false },
      { name: "Menge", type: "Edm.String", nullable: false, isKey: false },
      { name: "Meins", type: "Edm.String", nullable: false, isKey: false },
      { name: "Badat", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Lfdat", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Preis", type: "Edm.String", nullable: false, isKey: false },
      { name: "Peinh", type: "Edm.String", nullable: false, isKey: false },
      { name: "Flief", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ebeln", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ebelp", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bsmng", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ebakz", type: "Edm.Boolean", nullable: false, isKey: false },
      { name: "Rsnum", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "GoodsMovementItemSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "GoodsMovementItemSet",
    entityType: "GoodsMovementItem",
    keys: ["Mblnr","Mjahr","Zeile"],
    properties: [
      { name: "Mblnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Mjahr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Zeile", type: "Edm.String", nullable: false, isKey: true },
      { name: "Bwart", type: "Edm.String", nullable: false, isKey: false },
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: false },
      { name: "Lgort", type: "Edm.String", nullable: false, isKey: false },
      { name: "Lifnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Shkzg", type: "Edm.String", nullable: false, isKey: false },
      { name: "Dmbtr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Menge", type: "Edm.String", nullable: false, isKey: false },
      { name: "Meins", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ebeln", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ebelp", type: "Edm.String", nullable: false, isKey: false },
      { name: "Sgtxt", type: "Edm.String", nullable: false, isKey: false },
      { name: "Wempf", type: "Edm.String", nullable: false, isKey: false },
      { name: "Kostl", type: "Edm.String", nullable: false, isKey: false },
      { name: "Aufnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Rsnum", type: "Edm.String", nullable: false, isKey: false },
      { name: "Rspos", type: "Edm.String", nullable: false, isKey: false },
      { name: "Umwrk", type: "Edm.String", nullable: false, isKey: false },
      { name: "Umlgo", type: "Edm.String", nullable: false, isKey: false },
      { name: "Grund", type: "Edm.String", nullable: false, isKey: false },
      { name: "BudatMkpf", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "CpudtMkpf", type: "Edm.DateTime", nullable: true, isKey: false },
    ],
  },
  "InfoRecordSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "InfoRecordSet",
    entityType: "InfoRecord",
    keys: ["Infnr"],
    properties: [
      { name: "Infnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Lifnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Loekz", type: "Edm.Boolean", nullable: false, isKey: false },
    ],
  },
  "InfoRecordOrgSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "InfoRecordOrgSet",
    entityType: "InfoRecordOrg",
    keys: ["Ekorg","Esokz","Infnr"],
    properties: [
      { name: "Infnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Ekorg", type: "Edm.String", nullable: false, isKey: true },
      { name: "Esokz", type: "Edm.String", nullable: false, isKey: true },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: false },
      { name: "Loekz", type: "Edm.Boolean", nullable: false, isKey: false },
      { name: "Waers", type: "Edm.String", nullable: false, isKey: false },
      { name: "Aplfz", type: "Edm.String", nullable: false, isKey: false },
      { name: "Netpr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Peinh", type: "Edm.String", nullable: false, isKey: false },
      { name: "Effpr", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "PurchaseOrderSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "PurchaseOrderSet",
    entityType: "PurchaseOrder",
    keys: ["Ebeln"],
    properties: [
      { name: "Ebeln", type: "Edm.String", nullable: false, isKey: true },
      { name: "Bsart", type: "Edm.String", nullable: false, isKey: false },
      { name: "Aedat", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Lifnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ekorg", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ekgrp", type: "Edm.String", nullable: false, isKey: false },
      { name: "Waers", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "PurchaseOrderItemSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "PurchaseOrderItemSet",
    entityType: "PurchaseOrderItem",
    keys: ["Ebeln","Ebelp"],
    properties: [
      { name: "Ebeln", type: "Edm.String", nullable: false, isKey: true },
      { name: "Ebelp", type: "Edm.String", nullable: false, isKey: true },
      { name: "Loekz", type: "Edm.String", nullable: false, isKey: false },
      { name: "Txz01", type: "Edm.String", nullable: false, isKey: false },
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: false },
      { name: "Lgort", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bednr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Menge", type: "Edm.String", nullable: false, isKey: false },
      { name: "Meins", type: "Edm.String", nullable: false, isKey: false },
      { name: "Netpr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Peinh", type: "Edm.String", nullable: false, isKey: false },
      { name: "Netwr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Elikz", type: "Edm.Boolean", nullable: false, isKey: false },
      { name: "Pstyp", type: "Edm.String", nullable: false, isKey: false },
      { name: "Knttp", type: "Edm.String", nullable: false, isKey: false },
      { name: "Plifz", type: "Edm.String", nullable: false, isKey: false },
      { name: "Banfn", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bnfpo", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "VendorSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "VendorSet",
    entityType: "Vendor",
    keys: ["Lifnr"],
    properties: [
      { name: "Lifnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Name1", type: "Edm.String", nullable: false, isKey: false },
      { name: "Ktokk", type: "Edm.String", nullable: false, isKey: false },
      { name: "Loevm", type: "Edm.Boolean", nullable: false, isKey: false },
    ],
  },
  "MaterialDescriptionSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "MaterialDescriptionSet",
    entityType: "MaterialDescription",
    keys: ["Matnr","Spras"],
    properties: [
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Spras", type: "Edm.String", nullable: false, isKey: true },
      { name: "Maktx", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "MaterialSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "MaterialSet",
    entityType: "Material",
    keys: ["Matnr"],
    properties: [
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Lvorm", type: "Edm.Boolean", nullable: false, isKey: false },
      { name: "Mtart", type: "Edm.String", nullable: false, isKey: false },
      { name: "Matkl", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bismt", type: "Edm.String", nullable: false, isKey: false },
      { name: "Meins", type: "Edm.String", nullable: false, isKey: false },
      { name: "Mstae", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "MaterialPlantSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "MaterialPlantSet",
    entityType: "MaterialPlant",
    keys: ["Matnr","Werks"],
    properties: [
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: true },
      { name: "Lvorm", type: "Edm.Boolean", nullable: false, isKey: false },
      { name: "Dismm", type: "Edm.String", nullable: false, isKey: false },
      { name: "Dispo", type: "Edm.String", nullable: false, isKey: false },
      { name: "Plifz", type: "Edm.String", nullable: false, isKey: false },
      { name: "Webaz", type: "Edm.String", nullable: false, isKey: false },
      { name: "Minbe", type: "Edm.String", nullable: false, isKey: false },
      { name: "Eisbe", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bstmi", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bstma", type: "Edm.String", nullable: false, isKey: false },
      { name: "Mabst", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "StorageLocationStockSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "StorageLocationStockSet",
    entityType: "StorageLocationStock",
    keys: ["Lgort","Matnr","Werks"],
    properties: [
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: true },
      { name: "Lgort", type: "Edm.String", nullable: false, isKey: true },
      { name: "Labst", type: "Edm.String", nullable: false, isKey: false },
      { name: "Insme", type: "Edm.String", nullable: false, isKey: false },
      { name: "Speme", type: "Edm.String", nullable: false, isKey: false },
      { name: "Lgpbe", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "MaterialDocumentHeaderSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "MaterialDocumentHeaderSet",
    entityType: "MaterialDocumentHeader",
    keys: ["Mblnr","Mjahr"],
    properties: [
      { name: "Mblnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Mjahr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Budat", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Cpudt", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Xblnr", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "POScheduleLineSet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "POScheduleLineSet",
    entityType: "POScheduleLine",
    keys: ["Ebeln","Ebelp","Etenr"],
    properties: [
      { name: "Ebeln", type: "Edm.String", nullable: false, isKey: true },
      { name: "Ebelp", type: "Edm.String", nullable: false, isKey: true },
      { name: "Etenr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Eindt", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Menge", type: "Edm.String", nullable: false, isKey: false },
      { name: "Wemng", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "POHistorySet": {
    service: "ZVZI_KPI02_SHARED_SRV",
    entitySet: "POHistorySet",
    entityType: "POHistory",
    keys: ["Belnr","Buzei","Ebeln","Ebelp","Gjahr","Vgabe","Zekkn"],
    properties: [
      { name: "Ebeln", type: "Edm.String", nullable: false, isKey: true },
      { name: "Ebelp", type: "Edm.String", nullable: false, isKey: true },
      { name: "Zekkn", type: "Edm.String", nullable: false, isKey: true },
      { name: "Vgabe", type: "Edm.String", nullable: false, isKey: true },
      { name: "Gjahr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Belnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Buzei", type: "Edm.String", nullable: false, isKey: true },
      { name: "Bewtp", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bwart", type: "Edm.String", nullable: false, isKey: false },
      { name: "Budat", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Menge", type: "Edm.String", nullable: false, isKey: false },
      { name: "Dmbtr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Shkzg", type: "Edm.String", nullable: false, isKey: false },
      { name: "Cpudt", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "ReservationItemSet": {
    service: "ZMM_KPI02_SRV",
    entitySet: "ReservationItemSet",
    entityType: "ReservationItem",
    keys: ["Rsnum","Rspos"],
    properties: [
      { name: "Rsnum", type: "Edm.String", nullable: false, isKey: true },
      { name: "Rspos", type: "Edm.String", nullable: false, isKey: true },
      { name: "Xloek", type: "Edm.Boolean", nullable: false, isKey: false },
      { name: "Kzear", type: "Edm.Boolean", nullable: false, isKey: false },
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: false },
      { name: "Lgort", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bdter", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Bdmng", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Meins", type: "Edm.String", nullable: false, isKey: false },
      { name: "Enmng", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Enwrt", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Banfn", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bnfpo", type: "Edm.String", nullable: false, isKey: false },
      { name: "Aufnr", type: "Edm.String", nullable: false, isKey: false },
      { name: "Bwart", type: "Edm.String", nullable: false, isKey: false },
      { name: "Umwrk", type: "Edm.String", nullable: false, isKey: false },
      { name: "Umlgo", type: "Edm.String", nullable: false, isKey: false },
      { name: "Wempf", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "MaterialValuationSet": {
    service: "ZMM_KPI02_SRV",
    entitySet: "MaterialValuationSet",
    entityType: "MaterialValuation",
    keys: ["Bwkey","Matnr"],
    properties: [
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Bwkey", type: "Edm.String", nullable: false, isKey: true },
      { name: "Lbkum", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Salk3", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Vprsv", type: "Edm.String", nullable: false, isKey: false },
      { name: "Verpr", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Stprs", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Peinh", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Bklas", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "ChangeDocHeaderSet": {
    service: "ZMM_KPI02_SRV",
    entitySet: "ChangeDocHeaderSet",
    entityType: "ChangeDocHeader",
    keys: ["Changenr","Objectclas","Objectid"],
    properties: [
      { name: "Objectclas", type: "Edm.String", nullable: false, isKey: true },
      { name: "Objectid", type: "Edm.String", nullable: false, isKey: true },
      { name: "Changenr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Username", type: "Edm.String", nullable: false, isKey: false },
      { name: "Udate", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Utime", type: "Edm.Time", nullable: true, isKey: false },
      { name: "Tcode", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "ChangeDocItemSet": {
    service: "ZMM_KPI02_SRV",
    entitySet: "ChangeDocItemSet",
    entityType: "ChangeDocItem",
    keys: ["Changenr","Objectclas","Objectid"],
    properties: [
      { name: "Objectclas", type: "Edm.String", nullable: false, isKey: true },
      { name: "Objectid", type: "Edm.String", nullable: false, isKey: true },
      { name: "Changenr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Tabname", type: "Edm.String", nullable: false, isKey: false },
      { name: "Tabkey", type: "Edm.String", nullable: false, isKey: false },
      { name: "Fname", type: "Edm.String", nullable: false, isKey: false },
      { name: "Chngind", type: "Edm.String", nullable: false, isKey: false },
      { name: "Value_new", type: "Edm.String", nullable: false, isKey: false },
      { name: "Value_old", type: "Edm.String", nullable: false, isKey: false },
    ],
  },
  "BatchStockSet": {
    service: "ZMM_KPI02_SRV",
    entitySet: "BatchStockSet",
    entityType: "BatchStock",
    keys: ["Charg","Lgort","Matnr","Werks"],
    properties: [
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: true },
      { name: "Lgort", type: "Edm.String", nullable: false, isKey: true },
      { name: "Charg", type: "Edm.String", nullable: false, isKey: true },
      { name: "Clabs", type: "Edm.Decimal", nullable: false, isKey: false },
    ],
  },
  "MonthlyMovementStatisticSet": {
    service: "ZMM_KPI02_SRV",
    entitySet: "MonthlyMovementStatisticSet",
    entityType: "MonthlyMovementStatistic",
    keys: ["Lgort","Matnr","Spmon","Werks"],
    properties: [
      { name: "Spmon", type: "Edm.String", nullable: false, isKey: true },
      { name: "Werks", type: "Edm.String", nullable: false, isKey: true },
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Lgort", type: "Edm.String", nullable: false, isKey: true },
      { name: "Basme", type: "Edm.String", nullable: false, isKey: false },
      { name: "Mzubb", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Wzubb", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Magbb", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Wagbb", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Ambwg", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Muvbr", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Wuvbr", type: "Edm.Decimal", nullable: false, isKey: false },
    ],
  },
  "StockMovementStatisticSet": {
    service: "ZMM_KPI02_SRV",
    entitySet: "StockMovementStatisticSet",
    entityType: "StockMovementStatistic",
    keys: ["Lgort","Matnr","Werks"],
    properties: [
      { name: "Werks", type: "Edm.String", nullable: false, isKey: true },
      { name: "Lgort", type: "Edm.String", nullable: false, isKey: true },
      { name: "Matnr", type: "Edm.String", nullable: false, isKey: true },
      { name: "Dispo", type: "Edm.String", nullable: false, isKey: false },
      { name: "Mtart", type: "Edm.String", nullable: false, isKey: false },
      { name: "Matkl", type: "Edm.String", nullable: false, isKey: false },
      { name: "Dismm", type: "Edm.String", nullable: false, isKey: false },
      { name: "Mbwbest", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Wbwbest", type: "Edm.Decimal", nullable: false, isKey: false },
      { name: "Letztzug", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Letztabg", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Letztver", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Letztbew", type: "Edm.DateTime", nullable: true, isKey: false },
      { name: "Eisbe", type: "Edm.Decimal", nullable: false, isKey: false },
    ],
  },
}
