// Per-set readiness table (§10.13) — one page answering "what works today?"
// without reading code, and the checklist for flipping sets to live on Azure.
//
//   npm run readiness

import { writeFileSync, existsSync } from "node:fs"
import { SAP_CONTRACT } from "../src/lib/sap/contract/generated-contract"
import { readCounts } from "../src/lib/sap/contract/discovery-snapshot"
import { pagingConfigFor } from "../src/lib/sap/paging/config"
import { sourceFor } from "../src/lib/sap/routing"
import { EXPECTED_ABSENT_PROPERTIES } from "../src/lib/sap/contract/known-conditions"

const counts = readCounts()

interface Row {
  entitySet: string
  service: string
  properties: number
  rows: string
  countMode: string
  extract: string
  source: string
  fixture: string
  blocker: string
}

const rows: Row[] = Object.values(SAP_CONTRACT)
  .map((contract): Row => {
    const raw = counts[contract.entitySet] ?? "?"
    const paging = pagingConfigFor(contract.entitySet)
    const pending = EXPECTED_ABSENT_PROPERTIES.filter((p) => p.entitySet === contract.entitySet)

    const blockers: string[] = []
    if (raw === "0") blockers.push("returns zero rows (§1.3)")
    if (raw.startsWith("HTTP")) blockers.push(`$count ${raw}`)
    for (const p of pending) blockers.push(`${p.property} not exposed`)

    return {
      entitySet: contract.entitySet,
      service: contract.service.replace("_KPI02", "").replace("_SRV", ""),
      properties: contract.properties.length,
      rows: raw.startsWith("HTTP") ? "unknown" : Number(raw).toLocaleString("en-GB"),
      countMode: paging.countMode,
      extract: paging.extract,
      source: sourceFor(contract.entitySet),
      fixture: existsSync(`./data-generator/generated/sap/${contract.entitySet}.csv`) ? "yes" : "no",
      blocker: blockers.join("; ") || "—",
    }
  })
  .sort((a, b) => (a.blocker === "—" ? 1 : 0) - (b.blocker === "—" ? 1 : 0) || a.entitySet.localeCompare(b.entitySet))

const blocked = rows.filter((r) => r.blocker !== "—")

const lines = [
  "# Per-set readiness",
  "",
  "Generated by `npm run readiness`. One page answering \"what works today?\", and the",
  "checklist for flipping sets to live once Azure lands (order-of-work item 9).",
  "",
  `**${rows.length} entity sets. ${rows.length - blocked.length} have no blocker; ${blocked.length} do.**`,
  "",
  "| Entity set | Service | Fields | Live rows | $count | Extract | Serving | Fixture | Blocker |",
  "|---|---|---:|---:|---|---|---|---|---|",
  ...rows.map(
    (r) =>
      `| \`${r.entitySet}\` | ${r.service} | ${r.properties} | ${r.rows} | ${r.countMode} | ${r.extract} | ${r.source} | ${r.fixture} | ${r.blocker} |`
  ),
  "",
  "## Column meanings",
  "",
  "- **Live rows** — what `$count` returned on the last discovery sweep. `unknown` means",
  "  `$count` itself errors, so the row total is genuinely not knowable without a full read.",
  "- **$count** — `counted` asks SAP for a total; `fallback` never asks, and pages until a",
  "  short page; `auto` tries once and demotes itself, so a set self-promotes when SAP fixes it.",
  "- **Extract** — `filtered-only` sets refuse an unfiltered read outright. They are far too",
  "  large to pull whole (§1.4).",
  "- **Serving** — `mock` means the app is fed from generated fixtures; `live` means real CPI.",
  "  This is the dial in `src/lib/sap/routing.ts`. Flip one set at a time, running",
  "  `npm run smoke:cpi` after each.",
  "",
  "## Flipping a set to live",
  "",
  "1. Add it to `SET_SOURCES` in `src/lib/sap/routing.ts` as `\"live\"`.",
  "2. Run `npm run smoke:cpi`. A failure names the step.",
  "3. Check the set's blocker column first — a set that returns zero rows will render an",
  "   honest empty state, not an error, and that may not be what you want in a demo.",
  "",
  "**Flip the zero-row sets LAST.** Their schema is live but they hold no data, so moving",
  "them early trades working synthetic data for a legitimately empty screen.",
  "",
]

writeFileSync("./docs-eng/SET_READINESS.md", lines.join("\n"))
console.log(`Wrote docs-eng/SET_READINESS.md — ${rows.length} sets, ${blocked.length} with a blocker.`)
