// W2.6b — the gap report.
//
// "Where a fixture holds data no SAP field can produce, that is a finding:
// log it as a gap, do not invent a source." (§7.5)
//
// This turns the three source maps into one answer to the question nobody can
// currently answer without reading code: what is each screen actually made
// of, and which parts of it have no upstream producer at all?

import { RECOMMENDATION_SOURCES } from "./initiative-7"
import { REPAIR_CHAIN_SOURCES } from "./initiative-8"
import { LEDGER_LINE_SOURCES } from "./initiative-13"
import { toGapReportRows, type GapReportRow } from "./field-source"

export function buildGapReport(): GapReportRow[] {
  return [
    ...toGapReportRows("I07", "Recommendation", RECOMMENDATION_SOURCES),
    ...toGapReportRows("I08", "RepairChain", REPAIR_CHAIN_SOURCES),
    ...toGapReportRows("I13", "UtilizationLedgerLine", LEDGER_LINE_SOURCES),
  ]
}

export interface GapSummary {
  total: number
  sap: number
  platform: number
  derived: number
  blocked: number
  gap: number
}

export function summarise(rows: GapReportRow[]): GapSummary {
  const count = (kind: GapReportRow["source"]) => rows.filter((r) => r.source === kind).length
  return {
    total: rows.length,
    sap: count("sap"),
    platform: count("platform"),
    derived: count("derived"),
    blocked: count("blocked"),
    gap: count("gap"),
  }
}

export function formatGapReport(rows: GapReportRow[]): string {
  const summary = summarise(rows)
  const lines: string[] = [
    "# WS2 field-source gap report",
    "",
    "Generated by `npm run gap-report`. Every field of every initiative view model,",
    "and where its data comes from.",
    "",
    "| Source | Meaning | Fields |",
    "|---|---|---|",
    `| \`sap\` | A real, exposed SAP property | ${summary.sap} |`,
    `| \`platform\` | Data this system owns | ${summary.platform} |`,
    `| \`derived\` | Computed from other mapped fields | ${summary.derived} |`,
    `| \`blocked\` | Real SAP field, but no usable data yet (§1.3 / §1.7) | ${summary.blocked} |`,
    `| \`gap\` | **Nothing upstream produces this** | ${summary.gap} |`,
    `| | **Total** | **${summary.total}** |`,
    "",
  ]

  for (const initiative of ["I07", "I08", "I13"]) {
    const forInitiative = rows.filter((r) => r.initiative === initiative)
    if (forInitiative.length === 0) continue
    lines.push(`## ${initiative} — ${forInitiative[0].viewModel}`, "")
    lines.push("| Field | Source | Detail |", "|---|---|---|")
    for (const row of forInitiative) {
      const marker = row.source === "gap" ? "**gap**" : `\`${row.source}\``
      lines.push(`| \`${row.field}\` | ${marker} | ${row.detail.replace(/\|/g, "\\|")} |`)
    }
    lines.push("")
  }

  const gaps = rows.filter((r) => r.source === "gap")
  lines.push("## The gaps, in one place", "")
  lines.push(
    "These are the fields the UI renders today that nothing upstream can produce.",
    "Each is a decision: either something starts producing it, or the UI stops showing it.",
    ""
  )
  for (const row of gaps) {
    lines.push(`- **${row.initiative} \`${row.field}\`** — ${row.detail}`)
  }
  lines.push("")

  const blocked = rows.filter((r) => r.source === "blocked")
  lines.push("## Blocked on SAP, not missing", "")
  lines.push("These map to real SAP fields that exist but return nothing usable today.", "")
  for (const row of blocked) {
    lines.push(`- **${row.initiative} \`${row.field}\`** — ${row.detail}`)
  }
  lines.push("")

  return lines.join("\n")
}
