/**
 * The assistant, in demo mode.
 *
 * The assistant is a conversation of POSTs, and every one of them writes to an
 * append-only table, so its responses cannot be recorded the way the GETs are.
 * Instead demo mode replays the wire fixtures in lib/api/__fixtures__/ -- which
 * are themselves generated by the backend's own script and serialisers
 * (see that folder's README), so every step is byte-for-byte what the live
 * backend sends.
 *
 * There are two scripted conversations, one per flow:
 *
 *   I08  material 8000005632 @ 1300   session S7K2M4P8Q1
 *   I13  material 1000000123 @ 1300   session SQ4X9B2T7M
 *
 * An 80-series material opens the I08 one, anything else the I13 one, and the
 * branch taken follows the answer given. The fixtures' own material and
 * numbers are shown whatever was typed -- the demo banner says as much.
 */

import startI08 from "@/lib/api/__fixtures__/01-start-i08-choice.json"
import startI13 from "@/lib/api/__fixtures__/04-start-i13-choice.json"
import i08UseExisting from "@/lib/api/__fixtures__/06-answer-i08-use-existing.json"
import i08ProceedNew from "@/lib/api/__fixtures__/07-answer-i08-proceed-new.json"
import i08Justification from "@/lib/api/__fixtures__/08-answer-i08-justification.json"
import i13NotNeeded from "@/lib/api/__fixtures__/09-answer-i13-not-needed.json"
import i13Proceed from "@/lib/api/__fixtures__/10-answer-i13-proceed.json"
import i13CapturePlan from "@/lib/api/__fixtures__/11-answer-i13-capture-plan.json"
import i13AcceptSuggested from "@/lib/api/__fixtures__/12-answer-i13-accept-suggested.json"
import i13KeepRequested from "@/lib/api/__fixtures__/13-answer-i13-keep-requested.json"
import i13QuantityJustification from "@/lib/api/__fixtures__/14-answer-i13-quantity-justification.json"
import traceI13 from "@/lib/api/__fixtures__/16-session-trace-i13.json"
import traceI08 from "@/lib/api/__fixtures__/17-session-trace-i08.json"

type Answer = Record<string, unknown>

/** What the mock answers: a status and a JSON body. */
export type MockReply = { status: number; body: unknown }

const I08_SESSION = startI08.sessionId
const I13_SESSION = startI13.sessionId

export function startAssistantSession(body: { materialId?: unknown }): MockReply {
  const material = typeof body.materialId === "string" ? body.materialId.trim() : ""
  return { status: 200, body: material.startsWith("8") ? startI08 : startI13 }
}

/** The next step for an answer, chosen by session and by what was answered. */
export function answerAssistantTurn(sessionId: string, answer: Answer): MockReply {
  const choice = typeof answer.choice === "string" ? answer.choice : null

  if (sessionId === I08_SESSION) {
    if (choice === "use_existing") return created(i08UseExisting)
    if (choice === "proceed_new") return created(i08ProceedNew)
    if ("reason_category" in answer) return created(i08Justification)
  }
  if (sessionId === I13_SESSION) {
    if (choice === "not_needed") return created(i13NotNeeded)
    if (choice === "proceed") return created(i13Proceed)
    if ("purpose" in answer) return created(i13CapturePlan)
    if (choice === "accept_suggested") return created(i13AcceptSuggested)
    if (choice === "keep_requested") return created(i13KeepRequested)
    if ("reason_category" in answer) return created(i13QuantityJustification)
  }
  return {
    status: 404,
    body: { detail: `Session ${sessionId} is not one of the demo conversations. Start a new one.` },
  }
}

/** The trace behind a scripted session, or null for any other id. */
export function assistantSessionTrace(sessionId: string): MockReply | null {
  if (sessionId === I08_SESSION) return { status: 200, body: traceI08 }
  if (sessionId === I13_SESSION) return { status: 200, body: traceI13 }
  return null
}

/** The free-text box answers from live data only; say so rather than guess. */
export function askAssistant(): MockReply {
  return {
    status: 200,
    body: {
      intent: "demo_mode",
      answered: false,
      text: "Free-text questions are answered from live backend data, which demo mode does not call. Switch to Live data to ask this.",
      sources: [],
      data: {},
      suggestions: [],
      note: "Demo mode",
    },
  }
}

function created(body: unknown): MockReply {
  // The live route answers a turn with 201.
  return { status: 201, body }
}
